name: Daily Commit

on:
  schedule:
    - cron: "30 2 * * *"  # Runs at 02:30 UTC every day
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add a daily update file
        run: |
          echo "Daily update on $(date)" >> daily-update.txt
          git add daily-update.txt

      - name: Commit changes (24ds1000090@ds.study.iitm.ac.in)
        run: |
          git config --local user.email "24ds1000090@ds.study.iitm.ac.in"
          git config --local user.name "github-actions[bot]"
          git commit -m "Daily update on $(date)" || exit 0
          git push
