name: Daily Commit

on:
  schedule:
    - cron: "30 2 * * *"  # Runs at 02:30 UTC every day
  workflow_dispatch:

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to avoid conflicts

      - name: Add a daily update file
        run: |
          echo "Daily update on $(date)" >> daily-update.txt
          git add daily-update.txt

      - name: Commit and push changes (24ds1000090@ds.study.iitm.ac.in)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "24ds1000090@ds.study.iitm.ac.in"
          git config --local user.name "github-actions[bot]"
          git fetch origin main
          git reset --soft origin/main  # Keep changes but sync with remote
          git commit -m "Daily update on $(date)" || exit 0
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
