name: Test Action

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 24ds1000090@ds.study.iitm.ac.in
        run: echo "Hello, world!"
